### ISSUE TITLE
Switch back to Java 1.7 compatibility?

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/http-fetcher#13]
I'd like to use http-fetcher with some projects that are Java 1.7. I'm wondering if anyone has any strong feelings about keeping it at 1.8?

I've tried this, and other than a one line change everything compiles and tests fine.

**Comment by jnioche** [comment]
Hi @kkrugler no objections from me as long as the main project remains on 1.8

**Comment by kkrugler** [comment]
OK, I went ahead and made this change.
