### ISSUE TITLE
Fix fetching of robots.txt with https protocol

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/http-fetcher#18]
Examples include `http://rollingstone.com/robots.txt`, `http://forbes.com/robots.txt`, and `http://www.morningstar.com/robots.txt`. These redirect to `https://xxx`, and that fails with a `javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated` exception.

**Comment by aecio** [comment]
Closing, as it looks like this has been fixed in pull request #19.
