### ISSUE TITLE
Don't throw exceptions for HTTP errors

### ISSUE THREAD

**Issue by aecio** [crawler-commons/http-fetcher#7]
Bringing back issue crawler-commons/crawler-commons#86:

In our SimpleHttpFetcher, we check the status code, and when we encounter a status code not starting with "2" (non 2xx) we throw an Exception:
https://github.com/crawler-commons/http-fetcher/blob/master/src/main/java/crawlercommons/fetcher/http/SimpleHttpFetcher.java#L622-L626

Many times the page itself has html content which we should return to the user instead of throwing an exception.

For example: 404 pages...
Another example: status code: 500 page

Please note that when checking several other http clients - all of them returned the page even when status code was 4xx or 500 (maybe other cases also, I didn't check)

**Comment by kkrugler** [comment]
Fixed via pull request #10.
